# Generated by Django 5.2.5 on 2025-08-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_game_categories_favorite_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_game_of_year',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_updated',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('new', 'Новинки'), ('updated', 'Недавно обновлённые'), ('top', 'ТОП 250 игр'), ('year', 'Игры года')], default='new', max_length=16),
        ),
    ]
