# Generated by Django 5.2.5 on 2025-08-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_game_is_game_of_year_remove_game_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_review_status',
            field=models.CharField(choices=[('Очень положительные', 'Очень положительные'), ('Положительные', 'Положительные'), ('Смешанные', 'Смешанные'), ('Отрицательные', 'Отрицательные'), ('Нет данных', 'Нет данных')], default='Нет данных', help_text='Реальная оценка Steam для этой игры', max_length=32),
        ),
    ]
