# Generated by Django 5.2.5 on 2025-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_game_steam_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_appid',
            field=models.CharField(blank=True, help_text='Steam AppID для автоматического обновления статуса', max_length=16, null=True),
        ),
    ]
