# Generated by Django 5.2.5 on 2025-08-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_game_steam_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_review_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество отзывов Steam'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_review_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Процент положительных отзывов Steam'),
        ),
    ]
