# Generated by Django 5.2.5 on 2025-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_remove_game_category_game_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='torrents/'),
        ),
    ]
